-- DROP TABLE IF EXISTS bookmarks;
-- id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE star_rating AS ENUM ('1', '2', '3', '4', '5');

CREATE TABLE bookmarks (    
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    description TEXT,
    rating star_rating NOT NULL
);
